default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: illuminate_development

test:
  <<: *default
  database: illuminate_test

production:
  <<: *default
  database: illuminate_production
  username: illuminate
  password: <%= ENV['ILLUMINATE_DATABASE_PASSWORD'] %>
